version: "3"
services:
  web:
    build: .
    ports:
      - "3000:5173"
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json